### ISSUE TITLE
Could not enter new body after mindswapped after killed

### ISSUE THREAD

**Issue by Quantum-M** [ParadiseSS13/Paradise#10969]
**Problem Description**:
After being killed, changelings mindswapped my dead body, where afterwards, the body I was supposed to get I was not able to enter.

**What did you expect to happen**: 
To be able to enter the new body.

**What happened instead**:
Was not able to enter the new body and was told so when I hit the Enter body verb, or whatever  it is called.

**Why is this bad/What are the consequences:**
Unable to enter new body/perma death

**Steps to reproduce the problem**:
Die, ghost, have a changeling mindswap your dead body, try to enter the body you were supposed to enter and be unable to do so.

**When did the problem start happening**:
3/1/2019 is when it happened.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Changeling round.

**Comment by Pckables** [comment]
Was originally fixed by #9714 , but it sounds like a recent update broke it again.

**Comment by Aslan4468** [comment]
Just had this happen to me as HoS in a recent round. I'm surprised it isn't fixed considering how long ago this was made. It's very unfair to just be removed from the round when the cling mindswaps into your dead body and you can't get in theirs to fight back in any way, even with words if other officers have showed up.

**Comment by Rurik123** [comment]
As a note, this bug is still active.
