### ISSUE TITLE
Emitter beams pass through all types of reflectors

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#12713]
**Issue Description**:
See title

**What did you expect to happen**: 
For them to get reflected.

**What happened instead**:
They didn't get reflected.

**Why is this bad/What are the consequences**:
Makes reflectors worthless, engineers/atmos techs have less toys to play with.

**Steps to reproduce the problem**:
Fire an emitter at any of the reflector types.

**When did the problem start happening**:
Not sure, haven't used reflectors in a couple months

**Comment by moxian** [comment]
Should be fixed by #11800

**Comment by SteelSlayer** [comment]
Yep, this will be fixed my SSprojectiles, closing

**Comment by Couls** [comment]
don't close an issue if its not resolved yet, close it after SSprojectiles is merged

**Comment by FreeStylaLT** [comment]
This is now actually fixed, even without SSProjectiles by #12808

**Comment by SteelSlayer** [comment]
Right
