### ISSUE TITLE
Spell recharge effect for icons is broken

### ISSUE THREAD

**Issue by SteelSlayer** [ParadiseSS13/Paradise#14540]
**Issue Description**:

After spells go on cooldown, instead of lighting up gradually, and displaying the percent its recharged so far, it just flickers over and over until it comes back off cooldown. This happens with ALL spells from what I can tell.

![OfpyWwuA39](https://user-images.githubusercontent.com/42044220/95108094-69b81c00-0700-11eb-8712-0e7e13d9830b.gif)

**What did you expect to happen?**:
For the spell icons to behave like how they were tweaked in #13200.

**Steps to reproduce the problem**:
Click on any spell icon. Observe.

**When did the problem start happening**:
Very recently. Possibly as a result of #13621 being merged.

**Comment by S-CR** [comment]
Haha, I noticed this when doing #14543 but assumed it was working as intended for spooky boo effects.

**Comment by S-CR** [comment]
This can be closed, fixed by #14549

**Comment by SteelSlayer** [comment]
This is still an issue, although the flicker effect is reduced now:

![deHFZAI](https://user-images.githubusercontent.com/42044220/95537328-0570b300-09b3-11eb-8f2b-b79d0fdfc79a.gif)

And also as you can see weird stuff happens for spells you can't cast such as hypnotize being lit up and on 100% even though I don't have enough blood to cast it.
