### ISSUE TITLE
Pipe network is slightly broken in box perma, missing vent

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#21113]
**Issue Description**:

A pipe in perma leads to a non existant vent under the table

![image](https://github.com/ParadiseSS13/Paradise/assets/52090703/b039085e-84fd-4105-aca8-98692345376f)

**What did you expect to happen**: 

vent

**What happened instead**:

vent'nt

**Why is this bad/What are the consequences**:

vents should exist work as expected

**Steps to reproduce the problem**:

load the live server map

**When did the problem start happening**:

probably those north cyb maint prs

**Extra information**:

please let map diff bot have pipes again

**Comment by efzapa** [comment]
can fix this whenever I get home tonight

**Comment by warriorstar-orion** [comment]
Was fixed a while go

**Comment by Contrabang** [comment]
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/defafbb3-1df1-4ccd-9b3b-0ecffdad313a)
Its still not there on updated master
![image](https://github.com/ParadiseSS13/Paradise/assets/91113370/83959fc8-5b6c-4359-88e8-809ddf8c9a64)
