### ISSUE TITLE
bug with nutriant sprites

### ISSUE THREAD

**Issue by eeveerocks1000** [ParadiseSS13/Paradise#5742]
when I tried to get a bottle of easy nutriants from the nutri-max the sprite for it did not show up same with the robust harvest one... it happened yesterday too. 

you have to right click it to find it.... and even then the sprite dose not show up when you pick it up

**Comment by LittleBigKid2000** [comment]
This was fixed in #5691, which was merged 16 days ago.

**Comment by hinata447** [comment]
I still have the invisible sprites, is there something i have to update?

**Comment by LittleBigKid2000** [comment]
No, the server itself needs to update. There's nothing you can do on your end.

**Comment by hinata447** [comment]
thanks for the quick response!, so it hasn't rolled out yet?

**Comment by LittleBigKid2000** [comment]
Yes, the fix for the invisible bottles hasn't been rolled out to the server yet.
