### ISSUE TITLE
Corazone/Abductor surgery table does not prevent death by heart attack when heart is removed

### ISSUE THREAD

**Issue by datlo** [ParadiseSS13/Paradise#9198]
**Problem Description**:
What is the problem?

Surgery patient will still die of a heart attack when the heart is removed with corazone in the body.

**What did you expect to happen**: 
Why do you think this is a bug?

I expected the patient to be fine and to be able to insert a new organ as replacement.

**What happened instead**:
How is what happened different from what you expected?

Patient died, despite corazone being in the body.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Abductors cannot perform surgery without the patient dying, forcing them to steal a defibrillator to get any work done. 

This also affects any advanced surgeons doing heart surgery, although rarer.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

1. Abduct someone
2. Place on alien surgery table, see that the patient was injected with corazone by the alien surgery table
3. Perform surgery, remove heart
4. Patient die near instantly

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

This was reported by Ophelia Mason and tested on local server, copy of the current paradise github version. I have not tested this on live server, but I have no reasons to believe this isn't also an issue there.

**Comment by Fox-McCloud** [comment]
This isn't from having hearts removed.

This is because surgery produces ***obscene*** levels of germs, now that a bug regarding germs was fixed.

**Comment by datlo** [comment]
Oh, that makes sense. Well, it's still an issue, but a different one, I don't believe abductor scientist starts with gloves by default... Thanks for the help. I'll close this and open a different issue later after some more testing.
