### ISSUE TITLE
Paranormal ERT null rod

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#9971]
**Problem Description**:
When manually turning a mob into a paranormal ERT, they cannot change their null rod from base form.

**What did you expect to happen**: 
Like all chaplains/paranormal ERT, manually created paranormals should have the ability to change the null rod.

**What happened instead**:
Null rod cannot be changed.

**Why is this bad/What are the consequences:**
Players manually made paranormal ERT cannot select their null rod form.

**Steps to reproduce the problem**:
Get regular human mob, select equipment and gear them up as paranormal ERT member.  Cannot change null rod.

**Comment by Superhats** [comment]
I think that's because manually changing equipment doesn't give them the `SPECIAL_ROLE_ERT` flag
but, the null rod actually checks for this flag to determine if it can be changed

**Comment by variableundefined** [comment]
Probably best fixed by implementing a trait system.

**Comment by Kyep** [comment]
I think this has been fixed for awhile, and can be closed.

**Comment by Denthamos** [comment]
Still an issue.  Can verify as of last week, change equipment mode to change a mob into the paranormal ERT gear does not let the mob use ERT null rods as it does not change their mind datum to have the isholy=1.
